name: Docs

on:
  push:
    branches:
      - 'main'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 19.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - name: Setup npm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Build API-Docs
        run: npm run docs:build
        continue-on-error: true

      - name: Checkout repositório do GitHub Pages
        uses: actions/checkout@v3
        with:
          repository: calcme-community/calcme-community.github.io
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: gh-pages


      - name: Commit e Push para o GitHub Pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Atualizando API-Docs automaticamente" || echo "Nenhuma mudança para commitar"
          git push origin main
